version: '3.8'

services:
#  web:
#    image: python:3.10
#    container_name: python_web_app
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: python app.py
#    volumes:
#      - .:/app
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    env_file:
#      - .env

  db:
    image: postgres:13
    container_name: amichan_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data:
