version: '3.9'

services:
  amichan_api:
    container_name: amichan-api
    build: .
    command: uvicorn amichan.app:app --host 0.0.0.0 --port 8000
    environment:
      POSTGRES_HOST: amichan_db

    volumes:
      - .:/amichan
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    container_name: amichan_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data:
