"""Fix delete errors

Revision ID: 44a01e699d32
Revises: 2d28052b251c
Create Date: 2024-12-22 18:18:36.075284

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44a01e699d32"
down_revision: Union[str, None] = "2d28052b251c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "admins", ["id"])
    op.create_unique_constraint(None, "ban_list", ["id"])
    op.create_unique_constraint(None, "board", ["id"])
    op.create_unique_constraint(None, "file", ["id"])
    op.create_unique_constraint(None, "post", ["id"])
    op.create_unique_constraint(None, "role", ["id"])
    op.create_unique_constraint(None, "thread", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "thread", type_="unique")
    op.drop_constraint(None, "role", type_="unique")
    op.drop_constraint(None, "post", type_="unique")
    op.drop_constraint(None, "file", type_="unique")
    op.drop_constraint(None, "board", type_="unique")
    op.drop_constraint(None, "ban_list", type_="unique")
    op.drop_constraint(None, "admins", type_="unique")
    # ### end Alembic commands ###
